#Pandas Examples



Write a Pandas program to convert a Panda module Series to Python list and its type.

In [5]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))


Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [6]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]



In [7]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)


Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


Write a Pandas program to convert a dictionary to a Pandas series.
Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}


In [8]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)


Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


Write a Pandas program to convert a NumPy array to a Pandas series.
Sample NumPy array: d1 = [10, 20, 30, 40, 50]


In [9]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


Write a Pandas program to change the data type of the given  Series into numeric
['100', '200', 'python', '300.12', '400']


In [10]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)


Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


Write a Pandas program to convert a given Series to an array

In [11]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


Write a Pandas program to sort a given Series.

In [13]:
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)


Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


Write a Pandas program to add some data to an existing Series.

In [14]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


Write a Pandas program to create a subset of a given series based on value and condition.

In [15]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


Write a Pandas program to change the order of index of a given series.

In [16]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)


Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.

In [17]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())


Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565



Write a Pandas program to get the elements of an array values into column-wise.
Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}


In [18]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Numpy Examples

Write a NumPy program to generate five random numbers from the normal distribution.

In [20]:
import numpy as np
x = np.random.normal(size=5)
print(x)


[ 0.12323398 -0.66063218 -0.29374604 -0.35564671 -0.14412904]


Write a NumPy program to generate six random integers between 10 and 30

In [21]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[17 18 13 22 15 29]


Write a NumPy program to create a 3x3x3 array with random values.

In [22]:
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.5226228  0.769018   0.04357564]
  [0.36888253 0.32665242 0.11915811]
  [0.24562351 0.46315173 0.60313551]]

 [[0.92388135 0.28148437 0.76256235]
  [0.82509256 0.32146194 0.06860032]
  [0.96566387 0.1729446  0.98975595]]

 [[0.17256229 0.88522092 0.74763565]
  [0.64834824 0.19720976 0.99009433]
  [0.19360454 0.16211196 0.4792362 ]]]


Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

In [23]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.17520846 0.4559185  0.08423005 0.39115531 0.4029981 ]
 [0.14100141 0.23433464 0.97470372 0.9495028  0.77712226]
 [0.67451755 0.32908917 0.92842803 0.53603345 0.06188754]
 [0.12832798 0.90312587 0.87531756 0.64188355 0.84171142]
 [0.75052287 0.48215191 0.66855622 0.33688818 0.5945281 ]]
Minimum and Maximum Values:
0.061887540242621775 0.9747037241993582


Write a NumPy program to create a random 10x4 array and extract the first five rows of the # array and store them into a variable.

In [24]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)


Original array: 
[[0.74160304 0.47924894 0.55733821 0.5982245 ]
 [0.24236544 0.00898896 0.91439521 0.05335282]
 [0.0662185  0.99358555 0.58974027 0.41848902]
 [0.16445461 0.90434778 0.91560345 0.60274742]
 [0.11993524 0.37230636 0.98278503 0.69757799]
 [0.12617219 0.62346766 0.10053085 0.81453964]
 [0.50499957 0.12317765 0.79620657 0.20594712]
 [0.31905182 0.43723983 0.60565226 0.25481893]
 [0.44911405 0.59452916 0.16359589 0.59934233]
 [0.59212969 0.36307685 0.74794411 0.50845064]]
First 5 rows of the above array:
[[0.74160304 0.47924894 0.55733821 0.5982245 ]
 [0.24236544 0.00898896 0.91439521 0.05335282]
 [0.0662185  0.99358555 0.58974027 0.41848902]
 [0.16445461 0.90434778 0.91560345 0.60274742]
 [0.11993524 0.37230636 0.98278503 0.69757799]]
First 3 columns of the above array:
[[0.74160304 0.47924894 0.55733821 0.5982245 ]
 [0.24236544 0.00898896 0.91439521 0.05335282]
 [0.0662185  0.99358555 0.58974027 0.41848902]
 [0.16445461 0.90434778 0.91560345 0.60274742]
 [0.11993524 0.3723

Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).

In [25]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[6 3 8 1 9 2 7 5 4 0]
Same result using permutation():
[5 3 2 7 6 9 4 8 1 0]


Write a NumPy program to create a random integer nos of size 10 and sort it.

In [31]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)


[8 4 7 9 6 5 1 2 0 3]
[0 1 2 3 4 5 6 7 8 9]
