use List Comprehension ds = pd.Series([0,2, 4, 6, 8..... 10000])

In [1]:
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [2]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [3]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.

Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]

In [4]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


Write a Pandas program to convert a NumPy array to a Pandas series.

Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

In [5]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


Write a Pandas program to convert a given Series to an array.

Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [6]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


Write a Pandas program to sort a given Series.

Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [7]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


Write a Pandas program to create a subsets of a given series based on value and condition.

Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5

In [8]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [9]:
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


Write a Pandas program to get the elements of an array values into column-wise.

Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [10]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

In [11]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])

First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

In [19]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x)

Original Array:
[[0.50672662 0.338588   0.7353808  0.44576886]
 [0.01614311 0.24598408 0.10305687 0.37896995]
 [0.05859962 0.20358796 0.232968   0.16907634]
 [0.66199031 0.57620225 0.95004405 0.93774867]]


Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [20]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.10862292 0.8906626  0.27811061 0.70428513 0.41323708 0.70093329
  0.31685228 0.89980785 0.75005066 0.10458588]
 [0.3833256  0.24991798 0.40680334 0.24061547 0.7740034  0.0101097
  0.00163038 0.83595863 0.07187708 0.36177301]
 [0.6244015  0.02560703 0.23220292 0.23925487 0.4500422  0.00800319
  0.01418862 0.40914137 0.69625908 0.17942487]
 [0.06649347 0.51820856 0.78715945 0.68621036 0.01330541 0.16710119
  0.73095544 0.22162911 0.79610845 0.72769751]
 [0.71494029 0.61132757 0.40584722 0.77964934 0.8007021  0.10874682
  0.60723686 0.73855478 0.41877536 0.99706691]
 [0.34842478 0.65925726 0.49045864 0.73966571 0.00790658 0.73652345
  0.75231042 0.80645197 0.49673719 0.68943413]
 [0.82868942 0.24267654 0.96297456 0.68152556 0.5571584  0.2195392
  0.63927478 0.46168808 0.05545085 0.32201287]
 [0.67202224 0.83194031 0.88747034 0.53187563 0.64135729 0.10490515
  0.63337218 0.75717995 0.75943447 0.3343667 ]
 [0.4341648  0.56076599 0.89192875 0.33316095 0.33482971 0.884593


Write a NumPy program to generate 8 random integers between 100 and 300

In [21]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[194 194 163 157 266 189 234 105]


Write a NumPy program to create a random integer nos of size 20 and sort it.

In [22]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.10111894 0.84728172 0.53395978 0.40932222 0.4678759  0.72954556
 0.80431849 0.7112858  0.71482133 0.41283513 0.91089418 0.61132526
 0.73473843 0.16720175 0.87477053 0.82448624 0.16013402 0.39445471
 0.92758359 0.55527493]
Sorted array:
[0.10111894 0.16013402 0.16720175 0.39445471 0.40932222 0.41283513
 0.4678759  0.53395978 0.55527493 0.61132526 0.7112858  0.71482133
 0.72954556 0.73473843 0.80431849 0.82448624 0.84728172 0.87477053
 0.91089418 0.92758359]
